# Generated by Django 4.0.6 on 2022-07-14 20:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-100', max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscore or hyphens', max_length=150, verbose_name='Category Sfae URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(help_text='format: not required', on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='Parent of category')),
            ],
            options={
                'verbose_name': 'Produt category',
                'verbose_name_plural': 'Produt categories',
            },
        ),
    ]
